# Usar la imagen base de Anaconda3
FROM continuumio/anaconda3

# Establecer el directorio de trabajo
WORKDIR /opt/notebooks

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt /tmp/requirements.txt

# Instalar las dependencias desde requirements.txt
RUN conda install --yes --file /tmp/requirements.txt

# Exponer el puerto que usará Jupyter Notebook
EXPOSE 8888

# Comando para ejecutar Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/opt/notebooks"]