version: "3"

services:
  jupyter:
    build: .
    container_name: jupyter-anaconda
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
  db:
    build:
      context: ./etl
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ETL
    ports:
      - "3306:3306"
